server:
  port: 8080

spring:
  application:
    name: springboot_demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password:
  redis:
    host: localhost
    port: 6379
    password:

mybatis:
  mapperLocations: classpath:mapper/**/*.xml

logging:
  path: /data/logs/${spring.application.name}
  file: ${spring.application.name}.log
  level:
    root: INFO
